version: '3'

services:
  wrong-notebook:
    image: ghcr.io/robs87/wrong-notebook:latest
    container_name: wrong-notebook
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_SECRET=change_me_with_openssl_rand_base64_32
      - AUTH_TRUST_HOST=true
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
      - ./config:/app/config